### ISSUE TITLE
Can't use classy-prelude with GHCJS

### ISSUE THREAD

**Issue by mrijkeboer** [snoyberg/mono-traversable#102]
I would like to use classy-prelude with GHCJS, but unfortunately I can't get classy-prelude to compile with GHCJS. I get the following error:

```
--  While building package basic-prelude-0.5.2 using:
      /home/user/.stack/setup-exe-cache/x86_64-openbsd/setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-openbsd/Cabal-1.22.8.0_ghcjs build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/user/Checkouts/test/client/.stack-work/logs/basic-prelude-0.5.2.log

    Configuring basic-prelude-0.5.2...
    Building basic-prelude-0.5.2...
    Preprocessing library basic-prelude-0.5.2...
    
    /tmp/stack59336/basic-prelude-0.5.2/BasicPrelude.hs:150:18:
        Could not find module `Safe'
        Perhaps you haven't installed the "js" libraries for package `safe-0.3.9@safe_BjI3SxrMPD5F5AZ3gJB9mt'?
        Use -v to see a list of the files searched for.
```

I use the following stack.yaml:
```
resolver: lts-6.4

packages:
- '.'
extra-deps: []
extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
flags: {}
extra-package-dbs: []
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
```
