### ISSUE TITLE
Publish `mono-traversable` 1.0.21.0

### ISSUE THREAD

**Issue by jcmartin** [snoyberg/mono-traversable#253]
The version of `mono-traversable` on hackage is out of date, and it is preventing packages that depend on this patch to be able to be released on hackage and stackage as well.

@BebeSparkelSparkel

**Comment by BebeSparkelSparkel** [comment]
@snoyberg hackage username `WilliamRusnack` can you add perms please?

**Comment by snoyberg** [comment]
Added!

**Comment by Bodigrim** [comment]
It would be great to move forward with a release, because it is a prerequisite for `store` to get back in Stackage.

**Comment by BebeSparkelSparkel** [comment]
@snoyberg I was thinking about creating a workflow for this like (not complete just a draft) the below. Is there an appropriate hackage account (since it doesn't have tokens yet) or should one be created?

```yaml
name: Upload to Hackage

on:
  push:
    tags:
      - 'v*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up cabal
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.4'

      - name: Build dependencies
        run: cabal update && cabal build --only-dependencies

      - name: Build package
        run: cabal build

      - name: Generate sdist
        run: cabal sdist

      - name: Upload to Hackage
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
        run: |
          cabal upload dist-newstyle/sdist/mono-traversable-<version>.tar.gz
        # Note: Replace `<version>` with your actual package version or use environment variables.

      - name: Upload Documentation
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
        run: |
          cabal haddock --haddock-for-hackage
          cabal upload -d dist-newstyle/doc/html/mono-traversable-<version>-docs.tar.gz
```
